// Copyright 2025 The tt-iree Authors
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#include "iree/schema/tt_executable_builder_util.h"

#include <string.h>

#include "flatcc/flatcc_builder.h"

// Generated by iree-flatcc-cli from tt_executable_def.fbs
#include "tt_executable_def_builder.h"

// flatcc namespace wrapper
#define ns(x) FLATBUFFERS_WRAP_NAMESPACE(iree_tenstorrent_hal, x)

iree_status_t tt_iree_build_ttex_executable_def(
    iree_allocator_t allocator,
    iree_host_size_t entry_point_count,
    const tt_iree_ttex_entry_point_desc_t* entry_points,
    iree_byte_span_t* out_data) {
  if (!out_data) {
    return iree_make_status(IREE_STATUS_INVALID_ARGUMENT, "out_data is null");
  }
  memset(out_data, 0, sizeof(*out_data));

  if (entry_point_count > 0 && !entry_points) {
    return iree_make_status(IREE_STATUS_INVALID_ARGUMENT,
                            "entry_points is null with count > 0");
  }

  flatcc_builder_t builder;
  flatcc_builder_init(&builder);

  // Build ExecutableDef root
  ns(ExecutableDef_start_as_root(&builder));
  ns(ExecutableDef_version_add(&builder, 0));

  // Build entry_points vector
  ns(ExecutableDef_entry_points_start(&builder));
  for (iree_host_size_t i = 0; i < entry_point_count; ++i) {
    const tt_iree_ttex_entry_point_desc_t* ep = &entry_points[i];

    ns(ExecutableDef_entry_points_push_start(&builder));
    ns(EntryPointDef_name_create_str(&builder, ep->name ? ep->name : ""));
    ns(EntryPointDef_constant_count_add(&builder, ep->constant_count));
    ns(EntryPointDef_binding_count_add(&builder, ep->binding_count));
    ns(EntryPointDef_flags_add(&builder, ep->flags));
    ns(EntryPointDef_workgroup_size_x_add(&builder, ep->workgroup_size[0]));
    ns(EntryPointDef_workgroup_size_y_add(&builder, ep->workgroup_size[1]));
    ns(EntryPointDef_workgroup_size_z_add(&builder, ep->workgroup_size[2]));
    ns(EntryPointDef_builtin_add(&builder, ep->builtin_program));
    ns(ExecutableDef_entry_points_push_end(&builder));
  }
  ns(ExecutableDef_entry_points_end(&builder));

  ns(ExecutableDef_end_as_root(&builder));

  // Finalize into a contiguous buffer
  size_t flatcc_size = 0;
  void* flatcc_buf =
      flatcc_builder_finalize_aligned_buffer(&builder, &flatcc_size);
  if (!flatcc_buf || flatcc_size == 0) {
    flatcc_builder_clear(&builder);
    return iree_make_status(IREE_STATUS_INTERNAL,
                            "flatcc finalize failed (size=0)");
  }

  // Copy to IREE allocator-owned memory so caller can free uniformly
  uint8_t* dst = NULL;
  iree_status_t status =
      iree_allocator_malloc(allocator, flatcc_size, (void**)&dst);
  if (!iree_status_is_ok(status)) {
    flatcc_builder_aligned_free(flatcc_buf);
    flatcc_builder_clear(&builder);
    return status;
  }
  memcpy(dst, flatcc_buf, flatcc_size);

  out_data->data = dst;
  out_data->data_length = (iree_host_size_t)flatcc_size;

  flatcc_builder_aligned_free(flatcc_buf);
  flatcc_builder_clear(&builder);
  return iree_ok_status();
}
