// Copyright 2025 The tt-iree Authors
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#include "iree/hal/drivers/tenstorrent/tt_executable.h"

#include <string.h>

#include <string>
#include <vector>

#include "iree/base/api.h"
#include "iree/hal/drivers/tenstorrent/tt_device.h"
#include "iree/hal/drivers/tenstorrent/tt_executable_cache.h"
#include "iree/schema/tt_executable_builder_util.h"

#ifndef TT_IREE_ENABLE_MOCK
#include "tt-metalium/host_api.hpp"
#include "tt-metalium/tensor_accessor_args.hpp"
#include "tt-metalium/tt_metal.hpp"
#endif

// ---------------------------------------------------------------------------
// TTEX FlatBuffer headers (generated by iree-flatcc-cli)
// Conditionally included: only available when schema build is enabled.
// ---------------------------------------------------------------------------
#ifdef TT_IREE_ENABLE_TTEX
#include "tt_executable_def_reader.h"
#include "tt_executable_def_verifier.h"
#define ttex_ns(x) FLATBUFFERS_WRAP_NAMESPACE(iree_tenstorrent_hal, x)
#endif

//===----------------------------------------------------------------------===//
// Executable Structure
//===----------------------------------------------------------------------===//

typedef struct iree_hal_tt_executable_t {
  iree_hal_resource_t resource;
  iree_allocator_t host_allocator;
  iree_hal_device_t* device;

  // Owned copy of executable_data (TTEX FlatBuffer).
  // Entry point name pointers reference into this buffer, so it must
  // outlive the executable.  NULL for legacy path.
  uint8_t* owned_data;
  iree_host_size_t owned_data_length;

  iree_host_size_t entry_point_count;

  // Flexible array of entry points.  Allocated inline after this struct.
  iree_hal_tt_entry_point_t entry_points[];
} iree_hal_tt_executable_t;

// Forward declare vtable
extern const iree_hal_executable_vtable_t iree_hal_tt_executable_vtable;

static iree_hal_tt_executable_t* iree_hal_tt_executable_cast(
    iree_hal_executable_t* base) {
  IREE_HAL_ASSERT_TYPE(base, &iree_hal_tt_executable_vtable);
  return (iree_hal_tt_executable_t*)base;
}

//===----------------------------------------------------------------------===//
// Helper: Create TT-Metal Program from Source (JIT) — unchanged from existing
//===----------------------------------------------------------------------===//

#ifndef TT_IREE_ENABLE_MOCK
static iree_status_t iree_hal_tt_create_program_for_custom_sfpi_add(
    iree_hal_tt_kernel_params_t* params) {
  params->program = new tt::tt_metal::Program();
  tt::tt_metal::Program& program =
      *static_cast<tt::tt_metal::Program*>(params->program);

  tt::tt_metal::CoreCoord core_coord = {0, 0};
  tt::tt_metal::CoreRange core(core_coord);
  params->core_range_x = 1;
  params->core_range_y = 1;

  // Circular Buffers (3 CBs for elementwise binary ops)
  constexpr uint32_t tiles_per_cb = 2;
  constexpr uint32_t tile_size_bytes = 32 * 32 * 2;  // bfloat16

  tt::CBIndex src0_cb_index = tt::CBIndex::c_0;
  tt::tt_metal::CreateCircularBuffer(
      program, core,
      tt::tt_metal::CircularBufferConfig(
          tiles_per_cb * tile_size_bytes,
          {{src0_cb_index, tt::DataFormat::Float16_b}})
          .set_page_size(src0_cb_index, tile_size_bytes));

  tt::CBIndex src1_cb_index = tt::CBIndex::c_1;
  tt::tt_metal::CreateCircularBuffer(
      program, core,
      tt::tt_metal::CircularBufferConfig(
          tiles_per_cb * tile_size_bytes,
          {{src1_cb_index, tt::DataFormat::Float16_b}})
          .set_page_size(src1_cb_index, tile_size_bytes));

  tt::CBIndex dst_cb_index = tt::CBIndex::c_16;
  tt::tt_metal::CreateCircularBuffer(
      program, core,
      tt::tt_metal::CircularBufferConfig(
          tiles_per_cb * tile_size_bytes,
          {{dst_cb_index, tt::DataFormat::Float16_b}})
          .set_page_size(dst_cb_index, tile_size_bytes));

  std::vector<uint32_t> reader_compile_args;
  tt::tt_metal::TensorAccessorArgs::create_dram_interleaved().append_to(
      reader_compile_args);
  tt::tt_metal::TensorAccessorArgs::create_dram_interleaved().append_to(
      reader_compile_args);

  std::vector<uint32_t> writer_compile_args;
  tt::tt_metal::TensorAccessorArgs::create_dram_interleaved().append_to(
      writer_compile_args);

  params->reader_kernel_id = tt::tt_metal::CreateKernel(
      program,
      "tt_metal/programming_examples/custom_sfpi_add/kernels/dataflow/"
      "read_tiles.cpp",
      core,
      tt::tt_metal::DataMovementConfig{
          .processor = tt::tt_metal::DataMovementProcessor::RISCV_0,
          .noc = tt::tt_metal::NOC::RISCV_0_default,
          .compile_args = reader_compile_args});

  params->writer_kernel_id = tt::tt_metal::CreateKernel(
      program,
      "tt_metal/programming_examples/custom_sfpi_add/kernels/dataflow/"
      "write_tile.cpp",
      core,
      tt::tt_metal::DataMovementConfig{
          .processor = tt::tt_metal::DataMovementProcessor::RISCV_1,
          .noc = tt::tt_metal::NOC::RISCV_1_default,
          .compile_args = writer_compile_args});

  params->compute_kernel_id = tt::tt_metal::CreateKernel(
      program,
      "tt_metal/programming_examples/custom_sfpi_add/kernels/compute/"
      "tiles_add.cpp",
      core, tt::tt_metal::ComputeConfig{});

  return iree_ok_status();
}

static iree_status_t iree_hal_tt_create_program_for_bf16_matmul_32x32x32(
    iree_hal_tt_kernel_params_t* params) {
  params->program = new tt::tt_metal::Program();
  tt::tt_metal::Program& program =
      *static_cast<tt::tt_metal::Program*>(params->program);

  tt::tt_metal::CoreCoord core_coord = {0, 0};
  tt::tt_metal::CoreRange core(core_coord);
  params->core_range_x = 1;
  params->core_range_y = 1;

  constexpr uint32_t tile_size_bytes = 32 * 32 * 2;  // bfloat16

  tt::tt_metal::CreateCircularBuffer(
      program, core,
      tt::tt_metal::CircularBufferConfig(
          tile_size_bytes, {{tt::CBIndex::c_0, tt::DataFormat::Float16_b}})
          .set_page_size(tt::CBIndex::c_0, tile_size_bytes));
  tt::tt_metal::CreateCircularBuffer(
      program, core,
      tt::tt_metal::CircularBufferConfig(
          tile_size_bytes, {{tt::CBIndex::c_1, tt::DataFormat::Float16_b}})
          .set_page_size(tt::CBIndex::c_1, tile_size_bytes));
  tt::tt_metal::CreateCircularBuffer(
      program, core,
      tt::tt_metal::CircularBufferConfig(
          tile_size_bytes, {{tt::CBIndex::c_16, tt::DataFormat::Float16_b}})
          .set_page_size(tt::CBIndex::c_16, tile_size_bytes));

  params->reader_kernel_id = tt::tt_metal::CreateKernel(
      program,
      "tests/tt_metal/tt_metal/test_kernels/dataflow/reader_matmul_blocked.cpp",
      core,
      tt::tt_metal::DataMovementConfig{
          .processor = tt::tt_metal::DataMovementProcessor::RISCV_1,
          .noc = tt::tt_metal::NOC::RISCV_1_default});

  params->writer_kernel_id = tt::tt_metal::CreateKernel(
      program,
      "tt_metal/kernels/dataflow/writer_unary.cpp",
      core,
      tt::tt_metal::DataMovementConfig{
          .processor = tt::tt_metal::DataMovementProcessor::RISCV_0,
          .noc = tt::tt_metal::NOC::RISCV_0_default});

  std::vector<uint32_t> compute_kernel_args = {
      1,  // block_tile_dim
      1,  // dst_tile_rows
      1,  // dst_tile_cols
      1,  // block_cnt
      1,  // in0_block_tile_cnt
      1,  // in1_block_tile_cnt
      1,  // out_block_tile_cnt
  };
  params->compute_kernel_id = tt::tt_metal::CreateKernel(
      program,
      "tests/tt_metal/tt_metal/test_kernels/compute/matmul.cpp",
      core, tt::tt_metal::ComputeConfig{.compile_args = compute_kernel_args});

  return iree_ok_status();
}

static iree_status_t iree_hal_tt_create_program_for_builtin(
    iree_hal_device_t* device,
    uint32_t builtin_program,
    iree_hal_tt_kernel_params_t* params) {
  try {
    (void)device;
    params->builtin_program = builtin_program;
    switch (builtin_program) {
      case TT_IREE_TTEX_BUILTIN_PROGRAM_CUSTOM_SFPI_ADD:
        return iree_hal_tt_create_program_for_custom_sfpi_add(params);
      case TT_IREE_TTEX_BUILTIN_PROGRAM_BF16_MATMUL_32X32X32:
        return iree_hal_tt_create_program_for_bf16_matmul_32x32x32(params);
      case TT_IREE_TTEX_BUILTIN_PROGRAM_BF16_MATMUL_TILED:
        // The tiled matmul path builds a program at dispatch time because
        // shape and core-grid selection may depend on runtime constants.
        params->program = nullptr;
        return iree_ok_status();
      default:
        return iree_make_status(IREE_STATUS_INVALID_ARGUMENT,
                                "unsupported TTEX builtin program %u",
                                builtin_program);
    }
  } catch (const std::exception& e) {
    return iree_make_status(IREE_STATUS_INTERNAL,
                            "Failed to create TT-Metal program: %s", e.what());
  }
}
#endif

//===----------------------------------------------------------------------===//
// Vtable: export_count
//===----------------------------------------------------------------------===//

static iree_host_size_t iree_hal_tt_executable_export_count(
    iree_hal_executable_t* base_executable) {
  iree_hal_tt_executable_t* executable =
      iree_hal_tt_executable_cast(base_executable);
  return executable->entry_point_count;
}

//===----------------------------------------------------------------------===//
// Vtable: export_info
//===----------------------------------------------------------------------===//

static iree_status_t iree_hal_tt_executable_export_info(
    iree_hal_executable_t* base_executable,
    iree_hal_executable_export_ordinal_t export_ordinal,
    iree_hal_executable_export_info_t* out_info) {
  iree_hal_tt_executable_t* executable =
      iree_hal_tt_executable_cast(base_executable);
  if (!out_info) {
    return iree_make_status(IREE_STATUS_INVALID_ARGUMENT, "out_info is null");
  }
  if (export_ordinal >= executable->entry_point_count) {
    return iree_make_status(IREE_STATUS_OUT_OF_RANGE,
                            "export ordinal %u out of range (count=%zu)",
                            export_ordinal, executable->entry_point_count);
  }

  const iree_hal_tt_entry_point_t* ep =
      &executable->entry_points[export_ordinal];
  memset(out_info, 0, sizeof(*out_info));
  out_info->name = ep->name;
  out_info->flags = (iree_hal_executable_export_flags_t)ep->flags;
  out_info->constant_count = ep->constant_count;
  out_info->binding_count = ep->binding_count;
  out_info->workgroup_size[0] = ep->workgroup_size[0];
  out_info->workgroup_size[1] = ep->workgroup_size[1];
  out_info->workgroup_size[2] = ep->workgroup_size[2];
  return iree_ok_status();
}

//===----------------------------------------------------------------------===//
// Vtable: export_parameters
//===----------------------------------------------------------------------===//

static iree_status_t iree_hal_tt_executable_export_parameters(
    iree_hal_executable_t* base_executable,
    iree_hal_executable_export_ordinal_t export_ordinal,
    iree_host_size_t capacity,
    iree_hal_executable_export_parameter_t* out_parameters) {
  iree_hal_tt_executable_t* executable =
      iree_hal_tt_executable_cast(base_executable);
  if (export_ordinal >= executable->entry_point_count) {
    return iree_make_status(IREE_STATUS_OUT_OF_RANGE,
                            "export ordinal %u out of range", export_ordinal);
  }

  // PoC: report 0 parameters.  The constant_count and binding_count in
  // export_info are sufficient for IREE's dispatch validation.  Detailed
  // parameter descriptors (names, types) can be added when needed.
  (void)capacity;
  (void)out_parameters;
  return iree_ok_status();
}

//===----------------------------------------------------------------------===//
// Vtable: lookup_export_by_name
//===----------------------------------------------------------------------===//

static iree_status_t iree_hal_tt_executable_lookup_export_by_name(
    iree_hal_executable_t* base_executable,
    iree_string_view_t name,
    iree_hal_executable_export_ordinal_t* out_export_ordinal) {
  iree_hal_tt_executable_t* executable =
      iree_hal_tt_executable_cast(base_executable);
  if (!out_export_ordinal) {
    return iree_make_status(IREE_STATUS_INVALID_ARGUMENT,
                            "out_export_ordinal is null");
  }

  for (iree_host_size_t i = 0; i < executable->entry_point_count; ++i) {
    if (iree_string_view_equal(name, executable->entry_points[i].name)) {
      *out_export_ordinal = (iree_hal_executable_export_ordinal_t)i;
      return iree_ok_status();
    }
  }
  return iree_make_status(IREE_STATUS_NOT_FOUND,
                           "export '%.*s' not found",
                           (int)name.size, name.data);
}

//===----------------------------------------------------------------------===//
// Destroy
//===----------------------------------------------------------------------===//

static void iree_hal_tt_executable_destroy(
    iree_hal_executable_t* base_executable) {
  iree_hal_tt_executable_t* executable =
      iree_hal_tt_executable_cast(base_executable);

#ifndef TT_IREE_ENABLE_MOCK
  for (iree_host_size_t i = 0; i < executable->entry_point_count; ++i) {
    iree_hal_tt_kernel_params_t* kp =
        &executable->entry_points[i].kernel_params;
    if (kp->program) {
      delete static_cast<tt::tt_metal::Program*>(kp->program);
      kp->program = NULL;
    }
  }
#endif

  // Free owned FlatBuffer copy
  if (executable->owned_data) {
    iree_allocator_free(executable->host_allocator, executable->owned_data);
  }

  iree_allocator_free(executable->host_allocator, executable);
}

//===----------------------------------------------------------------------===//
// Vtable — all required fields for IREE v3.9.0
//===----------------------------------------------------------------------===//
// NOTE: In v3.9.0, iree_hal_executable_vtable_t includes:
//   destroy, export_count, export_info, export_parameters,
//   lookup_export_by_name
// Leaving any of these NULL risks a crash when IREE dispatches through
// the vtable (e.g. during vmfb loading or profiling).

const iree_hal_executable_vtable_t iree_hal_tt_executable_vtable = {
    .destroy = iree_hal_tt_executable_destroy,
    .export_count = iree_hal_tt_executable_export_count,
    .export_info = iree_hal_tt_executable_export_info,
    .export_parameters = iree_hal_tt_executable_export_parameters,
    .lookup_export_by_name = iree_hal_tt_executable_lookup_export_by_name,
};

//===----------------------------------------------------------------------===//
// Creation: Legacy path (no FlatBuffer, hardcoded single entry point)
//===----------------------------------------------------------------------===//

static iree_status_t iree_hal_tt_executable_create_legacy(
    iree_hal_device_t* device,
    const iree_hal_executable_params_t* params,
    iree_allocator_t host_allocator,
    iree_hal_executable_t** out_executable) {
  // Allocate with 1 entry point
  iree_host_size_t entry_point_count = 1;
  iree_host_size_t total_size =
      sizeof(iree_hal_tt_executable_t) +
      entry_point_count * sizeof(iree_hal_tt_entry_point_t);

  iree_hal_tt_executable_t* executable = NULL;
  IREE_RETURN_IF_ERROR(
      iree_allocator_malloc(host_allocator, total_size, (void**)&executable));
  memset(executable, 0, total_size);

  iree_hal_resource_initialize(&iree_hal_tt_executable_vtable,
                               &executable->resource);
  executable->host_allocator = host_allocator;
  executable->device = device;
  executable->owned_data = NULL;
  executable->owned_data_length = 0;
  executable->entry_point_count = entry_point_count;

  // Populate the single entry point with PoC defaults
  iree_hal_tt_entry_point_t* ep = &executable->entry_points[0];
  ep->name = iree_make_cstring_view("legacy_dispatch_0");
  ep->constant_count = 0;
  ep->binding_count = 3;  // in0, in1, out
  ep->flags = 0;
  ep->workgroup_size[0] = 1;
  ep->workgroup_size[1] = 1;
  ep->workgroup_size[2] = 1;
  ep->builtin_program = TT_IREE_TTEX_BUILTIN_PROGRAM_CUSTOM_SFPI_ADD;
  ep->builtin_m_tiles = 0;
  ep->builtin_n_tiles = 0;
  ep->builtin_k_tiles = 0;

#ifndef TT_IREE_ENABLE_MOCK
  iree_status_t status = iree_hal_tt_create_program_for_builtin(
      device, ep->builtin_program, &ep->kernel_params);
  if (!iree_status_is_ok(status)) {
    iree_hal_executable_destroy((iree_hal_executable_t*)executable);
    return status;
  }
#endif

  *out_executable = (iree_hal_executable_t*)executable;
  return iree_ok_status();
}

//===----------------------------------------------------------------------===//
// Creation: TTEX FlatBuffer path
//===----------------------------------------------------------------------===//

#ifdef TT_IREE_ENABLE_TTEX
static iree_status_t iree_hal_tt_executable_create_ttex(
    iree_hal_device_t* device,
    const iree_hal_executable_params_t* params,
    iree_allocator_t host_allocator,
    iree_hal_executable_t** out_executable) {
  const uint8_t* fb_data = params->executable_data.data;
  iree_host_size_t fb_size = params->executable_data.data_length;

  // 1) Verify TTEX FlatBuffer
  int verify_ret = ttex_ns(ExecutableDef_verify_as_root(fb_data, fb_size));
  if (verify_ret != 0) {
    return iree_make_status(IREE_STATUS_INVALID_ARGUMENT,
                            "TTEX FlatBuffer verification failed (code=%d)",
                            verify_ret);
  }

  // 2) Read entry point count
  ttex_ns(ExecutableDef_table_t) def =
      ttex_ns(ExecutableDef_as_root(fb_data));
  ttex_ns(EntryPointDef_vec_t) eps =
      ttex_ns(ExecutableDef_entry_points(def));
  iree_host_size_t ep_count = ttex_ns(EntryPointDef_vec_len(eps));
  if (ep_count == 0) {
    return iree_make_status(IREE_STATUS_INVALID_ARGUMENT,
                            "TTEX contains 0 entry points");
  }

  // 3) Allocate executable + flexible array
  iree_host_size_t total_size =
      sizeof(iree_hal_tt_executable_t) +
      ep_count * sizeof(iree_hal_tt_entry_point_t);

  iree_hal_tt_executable_t* executable = NULL;
  IREE_RETURN_IF_ERROR(
      iree_allocator_malloc(host_allocator, total_size, (void**)&executable));
  memset(executable, 0, total_size);

  iree_hal_resource_initialize(&iree_hal_tt_executable_vtable,
                               &executable->resource);
  executable->host_allocator = host_allocator;
  executable->device = device;
  executable->entry_point_count = ep_count;

  // 4) Copy executable_data (string pointers from reader reference this buffer)
  IREE_RETURN_IF_ERROR(iree_allocator_malloc(
      host_allocator, fb_size, (void**)&executable->owned_data));
  memcpy(executable->owned_data, fb_data, fb_size);
  executable->owned_data_length = fb_size;

  // 5) Re-parse from the owned copy (pointers are now stable)
  def = ttex_ns(ExecutableDef_as_root(executable->owned_data));
  eps = ttex_ns(ExecutableDef_entry_points(def));

  for (iree_host_size_t i = 0; i < ep_count; ++i) {
    ttex_ns(EntryPointDef_table_t) fb_ep =
        ttex_ns(EntryPointDef_vec_at(eps, i));
    iree_hal_tt_entry_point_t* ep = &executable->entry_points[i];

    // Name: points into owned_data
    const char* name_cstr = ttex_ns(EntryPointDef_name(fb_ep));
    ep->name = iree_make_cstring_view(name_cstr ? name_cstr : "");

    // HAL metadata
    ep->constant_count = ttex_ns(EntryPointDef_constant_count(fb_ep));
    ep->binding_count = ttex_ns(EntryPointDef_binding_count(fb_ep));
    ep->flags = ttex_ns(EntryPointDef_flags(fb_ep));

    // Workgroup size (scalars with defaults=1 in schema)
    ep->workgroup_size[0] = ttex_ns(EntryPointDef_workgroup_size_x(fb_ep));
    ep->workgroup_size[1] = ttex_ns(EntryPointDef_workgroup_size_y(fb_ep));
    ep->workgroup_size[2] = ttex_ns(EntryPointDef_workgroup_size_z(fb_ep));
    // Defensive: ensure non-zero (flatcc returns 0 for absent defaults
    // depending on version; our schema says default=1 but belt-and-suspenders)
    if (ep->workgroup_size[0] == 0) ep->workgroup_size[0] = 1;
    if (ep->workgroup_size[1] == 0) ep->workgroup_size[1] = 1;
    if (ep->workgroup_size[2] == 0) ep->workgroup_size[2] = 1;

    // Dispatch routing
    ep->builtin_program = ttex_ns(EntryPointDef_builtin(fb_ep));
    ep->builtin_m_tiles = ttex_ns(EntryPointDef_builtin_m_tiles(fb_ep));
    ep->builtin_n_tiles = ttex_ns(EntryPointDef_builtin_n_tiles(fb_ep));
    ep->builtin_k_tiles = ttex_ns(EntryPointDef_builtin_k_tiles(fb_ep));
    ep->kernel_params.builtin_m_tiles = ep->builtin_m_tiles;
    ep->kernel_params.builtin_n_tiles = ep->builtin_n_tiles;
    ep->kernel_params.builtin_k_tiles = ep->builtin_k_tiles;

    // Create TT-Metal program for this builtin
#ifndef TT_IREE_ENABLE_MOCK
    iree_status_t status = iree_hal_tt_create_program_for_builtin(
        device, ep->builtin_program, &ep->kernel_params);
    if (!iree_status_is_ok(status)) {
      // Cleanup already-created programs
      for (iree_host_size_t j = 0; j < i; ++j) {
        if (executable->entry_points[j].kernel_params.program) {
          delete static_cast<tt::tt_metal::Program*>(
              executable->entry_points[j].kernel_params.program);
        }
      }
      iree_allocator_free(host_allocator, executable->owned_data);
      iree_allocator_free(host_allocator, executable);
      return status;
    }
#endif
  }

  *out_executable = (iree_hal_executable_t*)executable;
  return iree_ok_status();
}
#endif  // TT_IREE_ENABLE_TTEX

//===----------------------------------------------------------------------===//
// Creation: entry point — dispatches by executable_format
//===----------------------------------------------------------------------===//

iree_status_t iree_hal_tt_executable_create(
    iree_hal_device_t* device,
    const iree_hal_executable_params_t* params,
    iree_allocator_t host_allocator,
    iree_hal_executable_t** out_executable) {
  IREE_ASSERT_ARGUMENT(device);
  IREE_ASSERT_ARGUMENT(params);
  IREE_ASSERT_ARGUMENT(out_executable);
  *out_executable = NULL;

#ifdef TT_IREE_ENABLE_TTEX
  // Primary path: TTEX FlatBuffer format
  if (iree_string_view_equal(
          params->executable_format,
          iree_make_cstring_view(IREE_HAL_TT_EXECUTABLE_FORMAT))) {
    if (params->executable_data.data == NULL ||
        params->executable_data.data_length == 0) {
      return iree_make_status(
          IREE_STATUS_INVALID_ARGUMENT,
          "executable_format is '%s' but executable_data is empty",
          IREE_HAL_TT_EXECUTABLE_FORMAT);
    }
    return iree_hal_tt_executable_create_ttex(
        device, params, host_allocator, out_executable);
  }
#endif

  // Legacy fallback: hardcoded PoC program
  // Handles: format=="TT-METAL", format=="" (dispatch_test), or unknown format
  return iree_hal_tt_executable_create_legacy(
      device, params, host_allocator, out_executable);
}

//===----------------------------------------------------------------------===//
// Internal: lookup kernel params (used by queue_execute)
//===----------------------------------------------------------------------===//

iree_status_t iree_hal_tt_executable_lookup_kernel_params(
    iree_hal_executable_t* base_executable,
    int32_t entry_point,
    const iree_hal_tt_kernel_params_t** out_params) {
  iree_hal_tt_executable_t* executable =
      iree_hal_tt_executable_cast(base_executable);

  if (entry_point < 0 ||
      (iree_host_size_t)entry_point >= executable->entry_point_count) {
    return iree_make_status(IREE_STATUS_OUT_OF_RANGE,
                            "invalid entry point ordinal %d (count=%zu)",
                            entry_point, executable->entry_point_count);
  }

  *out_params = &executable->entry_points[entry_point].kernel_params;
  return iree_ok_status();
}

iree_status_t iree_hal_tt_executable_lookup_kernel_params_mutable(
    iree_hal_executable_t* base_executable,
    int32_t entry_point,
    iree_hal_tt_kernel_params_t** out_params) {
  iree_hal_tt_executable_t* executable =
      iree_hal_tt_executable_cast(base_executable);

  if (entry_point < 0 ||
      (iree_host_size_t)entry_point >= executable->entry_point_count) {
    return iree_make_status(IREE_STATUS_OUT_OF_RANGE,
                            "invalid entry point ordinal %d (count=%zu)",
                            entry_point, executable->entry_point_count);
  }

  *out_params = &executable->entry_points[entry_point].kernel_params;
  return iree_ok_status();
}
